### ISSUE TITLE
Heresy!?

### ISSUE THREAD

**Issue by jorgensigvardsson** [troglobit/uemacs#1]
https://github.com/troglobit/uemacs/blob/2549a330b45fe8111ccc24a9b00a9fcae138b379/src/sys/unix/Makefile#L39

xemacs? Really? 😹

**Comment by troglobit** [comment]
Heh, I noticed that too.  Decided to keep it though because I wanted to keep the repo as pristine and close to the original as possible.  The Makefile was actually as close to the Ultrix original as I could keep it, really surprised me that the name was xemacs!  The Atari version is also called XEMACS[.TOS] but the VMS version is called UEMACS.EXE ... 

I chose `uemacs` as the repo name because of the orig. tarball from <https://github.com/larsbrinkhoff/emacs-history/tree/sources/Dave%20Conroy>, so I'm leaning towards using `uemacs` as the binary name as well.

The [MicroEMACS v3.6 repo](https://github.com/troglobit/MicroEMACS) (the one developed from this code base by Daniel Lawrence) use the binary name `me`.

What do you think?

**Comment by troglobit** [comment]
In the conversion to configure, just now, I changed the binary name to match the repo name; uemacs.

What do you think, should we attempt to go for an shorter one instead, like ue maybe?

**Comment by jorgensigvardsson** [comment]
The word `xemacs` is something I've typed a million times in shells (a long time ago). It didn't feel right, as it's a different (although related) program. Does anybody use xemacs these days? 🤔 

`uemacs` vs `ue` - well, I'm a sucker for clarity. `ue` was something called UltraEdit back in the days on Windows too. Damn shame the character µ isn't on regular/western keyboards. :)

**Comment by troglobit** [comment]
OK, `uemacs` it is then! :-)

... closing issue ...
